"use strict";
// The transformFactory class is a wrapper around the model types in Azure Media Services to make code look a lot cleaner
// when creating custom encoding transforms.  The goal of the transformFactory is to eliminate the need for declaring the odataType strings constantly 
// while working with the Typescript types that are generated by the Azure SDK auto generation code. 
// This helps to clean up your custom Transform code and keeps things neat.
// 
// NOTE: This is not complete list here, so feel free to add new codecs, formats, or preset types you would like to simplify in your code. 
var __assign = (this && this.__assign) || function () {
    __assign = Object.assign || function(t) {
        for (var s, i = 1, n = arguments.length; i < n; i++) {
            s = arguments[i];
            for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p))
                t[p] = s[p];
        }
        return t;
    };
    return __assign.apply(this, arguments);
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.createVideoOverlay = exports.createJobInputs = exports.createJobInputSequence = exports.createJobOutputAsset = exports.createJobInputHttp = exports.createJobInputClip = exports.createJobInputAsset = exports.createFromEachInputFile = exports.createFromAllInputFile = exports.createInputFile = exports.createSelectAudioTrackByAttribute = exports.createSelectAudioTrackById = exports.createTSFormat = exports.createMp4Format = exports.createVideoAnalyzerPreset = exports.createAudioAnalyzerPreset = exports.createBuiltInStandardEncoderPreset = exports.createStandardEncoderPreset = exports.createJpgFormat = exports.createJpgLayer = exports.createJpgImage = exports.createPngFormat = exports.createPngLayer = exports.createPngImage = exports.createAACaudio = exports.createH265Layer = exports.createH265Video = exports.createH264Layer = exports.createH264Video = exports.createCopyAudio = exports.createCopyVideo = void 0;
function createCopyVideo(video) {
    return __assign({ odataType: "#Microsoft.Media.CopyVideo" }, video);
}
exports.createCopyVideo = createCopyVideo;
function createCopyAudio(audio) {
    return __assign({ odataType: "#Microsoft.Media.CopyAudio" }, audio);
}
exports.createCopyAudio = createCopyAudio;
function createH264Video(video) {
    return __assign({ odataType: "#Microsoft.Media.H264Video" }, video);
}
exports.createH264Video = createH264Video;
function createH264Layer(layer) {
    return __assign({}, layer);
}
exports.createH264Layer = createH264Layer;
function createH265Video(video) {
    return __assign({ odataType: "#Microsoft.Media.H265Video" }, video);
}
exports.createH265Video = createH265Video;
function createH265Layer(layer) {
    return __assign({}, layer);
}
exports.createH265Layer = createH265Layer;
function createAACaudio(audio) {
    return __assign({ odataType: "#Microsoft.Media.AacAudio" }, audio);
}
exports.createAACaudio = createAACaudio;
function createPngImage(image) {
    return __assign({ odataType: "#Microsoft.Media.PngImage" }, image);
}
exports.createPngImage = createPngImage;
function createPngLayer(image) {
    return __assign({}, image);
}
exports.createPngLayer = createPngLayer;
function createPngFormat(pngFormat) {
    return __assign({ odataType: "#Microsoft.Media.PngFormat" }, pngFormat);
}
exports.createPngFormat = createPngFormat;
function createJpgImage(image) {
    return __assign({ odataType: "#Microsoft.Media.JpgImage" }, image);
}
exports.createJpgImage = createJpgImage;
function createJpgLayer(image) {
    return __assign({}, image);
}
exports.createJpgLayer = createJpgLayer;
function createJpgFormat(format) {
    return __assign({ odataType: "#Microsoft.Media.JpgFormat" }, format);
}
exports.createJpgFormat = createJpgFormat;
function createStandardEncoderPreset(standardEncoder) {
    return __assign({ odataType: "#Microsoft.Media.StandardEncoderPreset" }, standardEncoder);
}
exports.createStandardEncoderPreset = createStandardEncoderPreset;
function createBuiltInStandardEncoderPreset(builtInStandardEncoder) {
    return __assign({ odataType: "#Microsoft.Media.BuiltInStandardEncoderPreset" }, builtInStandardEncoder);
}
exports.createBuiltInStandardEncoderPreset = createBuiltInStandardEncoderPreset;
function createAudioAnalyzerPreset(audioAnalyserPreset) {
    return __assign({ odataType: "#Microsoft.Media.AudioAnalyzerPreset" }, audioAnalyserPreset);
}
exports.createAudioAnalyzerPreset = createAudioAnalyzerPreset;
function createVideoAnalyzerPreset(videoAnalyserPreset) {
    return __assign({ odataType: "#Microsoft.Media.VideoAnalyzerPreset" }, videoAnalyserPreset);
}
exports.createVideoAnalyzerPreset = createVideoAnalyzerPreset;
function createMp4Format(mp4Format) {
    return __assign({ odataType: "#Microsoft.Media.Mp4Format" }, mp4Format);
}
exports.createMp4Format = createMp4Format;
function createTSFormat(tsFormat) {
    return __assign({ odataType: "#Microsoft.Media.TransportStreamFormat" }, tsFormat);
}
exports.createTSFormat = createTSFormat;
function createSelectAudioTrackById(audioTrackById) {
    return __assign({ odataType: "#Microsoft.Media.SelectAudioTrackById" }, audioTrackById);
}
exports.createSelectAudioTrackById = createSelectAudioTrackById;
function createSelectAudioTrackByAttribute(audioTrackByAttribute) {
    return __assign({ odataType: "#Microsoft.Media.SelectAudioTrackByAttribute" }, audioTrackByAttribute);
}
exports.createSelectAudioTrackByAttribute = createSelectAudioTrackByAttribute;
function createInputFile(inputFile) {
    return __assign({ odataType: "#Microsoft.Media.InputFile" }, inputFile);
}
exports.createInputFile = createInputFile;
function createFromAllInputFile(fromAllInputFile) {
    return __assign({ odataType: "#Microsoft.Media.FromAllInputFile" }, fromAllInputFile);
}
exports.createFromAllInputFile = createFromAllInputFile;
function createFromEachInputFile(fromEachInputFile) {
    return __assign({ odataType: "#Microsoft.Media.FromEachInputFile" }, fromEachInputFile);
}
exports.createFromEachInputFile = createFromEachInputFile;
function createJobInputAsset(inputAsset) {
    return __assign({ odataType: "#Microsoft.Media.JobInputAsset" }, inputAsset);
}
exports.createJobInputAsset = createJobInputAsset;
function createJobInputClip(inputAsset) {
    return __assign({ odataType: "#Microsoft.Media.JobInputClip" }, inputAsset);
}
exports.createJobInputClip = createJobInputClip;
function createJobInputHttp(inputHttp) {
    return __assign({ odataType: "#Microsoft.Media.JobInputHttp" }, inputHttp);
}
exports.createJobInputHttp = createJobInputHttp;
function createJobOutputAsset(outputAsset) {
    return __assign({ odataType: "#Microsoft.Media.JobOutputAsset" }, outputAsset);
}
exports.createJobOutputAsset = createJobOutputAsset;
function createJobInputSequence(jobInputSequence) {
    return __assign({ odataType: "#Microsoft.Media.JobInputSequence" }, jobInputSequence);
}
exports.createJobInputSequence = createJobInputSequence;
function createJobInputs(jobInputs) {
    return __assign({ odataType: "#Microsoft.Media.JobInputs" }, jobInputs);
}
exports.createJobInputs = createJobInputs;
function createVideoOverlay(videoOverlay) {
    return __assign({ odataType: "#Microsoft.Media.VideoOverlay" }, videoOverlay);
}
exports.createVideoOverlay = createVideoOverlay;